class DuplicateServer(Exception): ...


class NonEmptyServer(Exception): ...


class GPUlessServer(Exception): ...


class DeploymentFailure(Exception): ...


class GraValBootstrapFailure(Exception): ...
